services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\AiLlmsTxt\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  WebVision\AiLlmsTxt\Controller\LlmsTxtController:
    public: true
