services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FGTCLB\LlmsTxt\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Controllers
  FGTCLB\LlmsTxt\Controller\LlmsTxtController:
    public: true
